export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const SUCCESS = "ALERT_SUCCESS";
export const ERROR = "ALERT_ERROR";
export const CLEAR = "ALERT_CLEAR";

//CREATE SCHOOL ACCOUNT
// const CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST";
// const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
// const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";

//LIST OF TEACHERS
export const FETCH_TEACHERS_SUCCESS = "FETCH_TEACHERS_SUCCESS";
export const FETCH_TEACHERS_REQUEST = "FETCH_TEACHERS_REQUEST";
export const FETCH_TEACHERS_FAILURE = "FETCH_TEACHERS_FAILURE";
//FETCH SINGLE TEACHER
export const FETCH_SINGLE_TEACHER_SUCCESS = "FETCH_SINGLE_TEACHER_SUCCESS";
export const FETCH_SINGLE_TEACHER_REQUEST = "FETCH_SINGLE_TEACHER_REQUEST";
export const FETCH_SINGLE_TEACHER_FAILURE = "FETCH_SINGLE_TEACHER_FAILURE";
//DELETE TEACHER
export const DELETE_TEACHER_REQUEST = "DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAILURE = "DELETE_TEACHER_FAILURE";

//LIST OF ALL STUDENTS
export const FETCH_STUDENTS_SUCCESS = "FETCH_STUDENTS_SUCCESS";
export const FETCH_STUDENTS_REQUEST = "FETCH_STUDENTS_REQUEST";
export const FETCH_STUDENTS_FAILURE = "FETCH_STUDENTS_FAILURE";
//LIST OF  SINGLE STUDENT
export const FETCH_SINGLE_STUDENT_SUCCESS = "FETCH_SINGLE_STUDENT_SUCCESS";
export const FETCH_SINGLE_STUDENT_REQUEST = "FETCH_SINGLE_STUDENT_REQUEST";
export const FETCH_SINGLE_STUDENT_FAILURE = "FETCH_SINGLE_STUDENT_FAILURE";
//DELETE STUDENT
export const DELETE_STUDENT_SUCCESS = "FETCH_SINGLE_STUDENT_SUCCESS";
export const DELETE_STUDENT_REQUEST = "FETCH_SINGLE_STUDENT_REQUEST";
export const DELETE_STUDENT_FAILURE = "FETCH_SINGLE_STUDENT_FAILURE";
//UPDATE STUDENT
export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR";

// CLASSESS
export const FETCH_CLASS_REQUEST = "FETCH_CLASS_REQUEST";
export const FETCH_CLASS_SUCCESS = "FETCH_CLASS_SUCCESS";
export const FETCH_CLASS_FAILURE = "FETCH_CLASS_FAILURE";

export const DELETE_CLASS_REQUEST = "DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAILURE = "DELETE_CLASS_FAILURE";

// SUBJECT CONST
export const FETCH_SUBJECTS_REQUEST = "FETCH_SUBJECTS_REQUEST";
export const FETCH_SUBJECTS_SUCCESS = "FETCH_SUBJECTS_SUCCESS";
export const FETCH_SUBJECTS_FAILURE = "FETCH_SUBJECTS_FAILURE";

// DELETE SUBJECT
export const DELETE_SUBJECT_REQUEST = "DELETE_SUBJECT_REQUEST";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAILURE = "DELETE_SUBJECT_FAILURE";
